#planner stage
ARG     TAG=dev
FROM    hyperledger/iroha2-base:$TAG AS planner

WORKDIR /iroha
COPY    . .
RUN     cargo chef prepare --recipe-path recipe.json
RUN     cargo chef cook --profile deploy --target x86_64-unknown-linux-musl --features vendored --recipe-path recipe.json
