ARG TAG
FROM    hyperledger/iroha2-base:$TAG
WORKDIR /iroha
COPY    . .
RUN     rm -f rust-toolchain.toml
RUN     mold --run cargo build --profile deploy --target x86_64-unknown-linux-musl --features vendored
