[package]
name = "iroha_core"

edition.workspace = true
version.workspace = true
authors.workspace = true

description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

license.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[features]
# Support lightweight telemetry, including diagnostics
telemetry = []
# Support Prometheus metrics. See https://prometheus.io/.
expensive-telemetry = ["iroha_telemetry/metric-instrumentation"]
# Profiler integration for wasmtime
profiling = []

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_data_model = { workspace = true, features = ["transparent_api"] }
iroha_macro = { workspace = true }
iroha_p2p = { workspace = true }
iroha_logger = { workspace = true }
iroha_crypto = { workspace = true }
iroha_version = { workspace = true }
iroha_config = { workspace = true }
iroha_futures = { workspace = true }
iroha_telemetry = { workspace = true }
iroha_primitives = { workspace = true }
iroha_genesis = { workspace = true }
iroha_wasm_codec = { workspace = true }
mv = { workspace = true, features = ["serde"] }

async-trait = { workspace = true }
dashmap = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true, features = ["std", "async-await"] }
parity-scale-codec = { workspace = true, features = ["derive"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync", "time", "rt", "io-util", "rt-multi-thread", "macros", "fs"] }
crossbeam-queue = { workspace = true }
thiserror = { workspace = true }
displaydoc = { workspace = true }
wasmtime = { workspace = true }
parking_lot = { workspace = true, features = ["deadlock_detection"] }
derive_more = { workspace = true }
nonzero_ext = { workspace = true }

uuid = { version = "1.10.0", features = ["v4"] }
indexmap = "2.2.6"

[dev-dependencies]
iroha_executor_data_model = { workspace = true }
iroha_test_samples = { workspace = true }

criterion = { workspace = true }
hex = { workspace = true }
tempfile = { workspace = true }

byte-unit = "5.1.4"

[[bench]]
name = "validation"
harness = false

[[bench]]
name = "kura"
harness = false

[[bench]]
name = "apply_blocks"
harness = false
path = "benches/blocks/apply_blocks_benchmark.rs"

[[bench]]
name = "validate_blocks"
harness = false
path = "benches/blocks/validate_blocks_benchmark.rs"

[[example]]
name = "apply_blocks"
harness = false
path = "benches/blocks/apply_blocks_oneshot.rs"

[[example]]
name = "validate_blocks"
harness = false
path = "benches/blocks/validate_blocks_oneshot.rs"

[package.metadata.cargo-all-features]
denylist = [
    "schema-endpoint",
    "telemetry",
]
skip_optional_dependencies = true
