[package]
name = "iroha"

edition.workspace = true
version.workspace = true
authors.workspace = true

description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

license.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[features]
# Use rustls by default to avoid OpenSSL dependency, simplifying compilation with musl
default = ["tls-rustls-native-roots"]

tls-native = [
    "attohttpc/tls-native",
    "tokio-tungstenite/native-tls",
    "tungstenite/native-tls",
]
tls-native-vendored = [
    "attohttpc/tls-native-vendored",
    "tokio-tungstenite/native-tls-vendored",
    "tungstenite/native-tls-vendored",
]
tls-rustls-native-roots = [
    "attohttpc/tls-rustls-native-roots",
    "tokio-tungstenite/rustls-tls-native-roots",
    "tungstenite/rustls-tls-native-roots",
]
tls-rustls-webpki-roots = [
    "attohttpc/tls-rustls-webpki-roots",
    "tokio-tungstenite/rustls-tls-webpki-roots",
    "tungstenite/rustls-tls-webpki-roots",
]

[dependencies]
iroha_config = { workspace = true }
iroha_config_base = { workspace = true }
iroha_crypto = { workspace = true }
# FIXME: should remove `transparent_api` feature. Check the other FIXME comment in dev-dependencies
iroha_data_model = { workspace = true, features = ["http", "transparent_api"] }
iroha_executor_data_model = { workspace = true }
iroha_primitives = { workspace = true }
iroha_logger = { workspace = true }
iroha_telemetry = { workspace = true }
iroha_torii_const = { workspace = true }
iroha_version = { workspace = true }
iroha_test_samples = { workspace = true }

attohttpc = { version = "0.28.0", default-features = false }
eyre = { workspace = true }
error-stack = { workspace = true }
http = "1.1.0"
url = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
thiserror = { workspace = true }
displaydoc = { workspace = true }
derive_more = { workspace = true }
parity-scale-codec = { workspace = true, default-features = false, features = ["derive"] }
tokio = { workspace = true, features = ["rt"] }
tokio-tungstenite = { workspace = true }
tungstenite = { workspace = true }
futures-util = "0.3.30"
toml = { workspace = true }
nonzero_ext = { workspace = true }

[dev-dependencies]
iroha_genesis = { workspace = true }
iroha_test_network = { workspace = true }
executor_custom_data_model = { version = "=2.0.0-rc.1.0", path = "../../wasm_samples/executor_custom_data_model" }

tokio = { workspace = true, features = ["rt-multi-thread"] }
reqwest = { version = "0.12.7", features = ["json"] }
color-eyre = { workspace = true }
tempfile = { workspace = true }
hex = { workspace = true }
assertables = { workspace = true }
trybuild = { workspace = true }
assert_matches = "1.5.0"
