@startuml
Client --> Torii: Transaction with Transfer Asset Command
Torii --> Transaction: Stateless Validation
alt transaction valid
  Torii --> PendingTxCache: Valid Transaction
  Torii --> Client: Ok Message
  ... every round or on cache fill ..
  PendingTxCache --> Consensus: All Pending Transactions 
  Consensus --> Transactions: Statefull Validation and Sign
  Consensus --> Blockchain: Signed Transactions
  Blockchain --> Kura: Accepted Blocks
  Kura --> Disk: Accepted Blocks
  Kura --> WorldStateView: Accepted Blocks
else
  Torii --> Client: Error Message
@enduml
