[package]
name = "iroha_test_network"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[dependencies]
iroha_core.workspace = true
iroha.workspace = true

iroha_executor_data_model.workspace = true
iroha_crypto.workspace = true
iroha_config.workspace = true
iroha_data_model.workspace = true
iroha_primitives.workspace = true
iroha_logger.workspace = true
iroha_genesis.workspace = true
iroha_futures.workspace = true
iroha_test_samples.workspace = true
iroha_telemetry.workspace = true

color-eyre.workspace = true
thiserror.workspace = true
rand.workspace = true
tempfile.workspace = true
unique_port = "0.2.1"
serde_json.workspace = true
parity-scale-codec = { version = "3.6.12", default-features = false }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "process", "sync", "io-util"] }
futures = { workspace = true, features = ["std", "async-await"] }
toml = { workspace = true }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
fslock = "0.2.1"
serde = { workspace = true, features = ["derive"] }
derive_more = { workspace = true }
which = "6.0.3"
nix = { version = "0.29.0", features = ["signal"] }
