[tasks.test]
command = "cargo"
args = ["test", "--verbose", "--", "--nocapture"]

[tasks.cleanup-blocks]
env = { "BLOCKS_DIR" = "./blocks/" }
script_runner = "@shell"
script = [
    "rm -Rf ${BLOCKS_DIR}"
]

[tasks.test-flow]
dependencies = [
    "test",
    "cleanup-blocks"
]