#%RAML 1.0
---
title: Iroha Commands and Queries API
version: v2
baseUri: http://127.0.0.1:1337/
/commands:
  post:
    description: Submit a transaction with commands
    body:
      binary/scale:
        example: !include client_tranasction.request
    responses:
      200:
/queries:
  /assets:
    get:
    /{asset_id}:
      get:
        description: Retrieve a specific asset by its' identification
        responses:
          200:
