name: publish/what?

on:
  push:
    tags:
      - 'v2*'

env:
  CARGO_TERM_COLOR: always
  DOCKER_COMPOSE_PATH: defaults

jobs:
  build_executor:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2024-09-09
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Build iroha executor
        run: mold --run cargo run --bin iroha_wasm_builder -- build ./wasm_samples/default_executor --optimize --out-file ${{ env.DOCKER_COMPOSE_PATH }}/executor.wasm
      - name: Upload executor to reuse in other jobs
        uses: actions/upload-artifact@v4
        with:
          name: executor.wasm
          path: ${{ env.DOCKER_COMPOSE_PATH }}/executor.wasm
          retention-days: 1

  registry:
    runs-on: ubuntu-latest
    needs: build_executor
    steps:
      - uses: actions/checkout@v4
      - name: Download executor.wasm file
        uses: actions/download-artifact@v4
        with:
          name: executor.wasm
          path: ${{ env.DOCKER_COMPOSE_PATH }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Get the release tag
        run: |
          RELEASE_VERSION=${{ github.ref_name }}
          PREFIX='v'
          TAG=${RELEASE_VERSION#$PREFIX}
          echo "TAG=$TAG" >>$GITHUB_ENV
      - name: Build and export to Docker iroha2 image
        uses: docker/build-push-action@v6
        if: always()
        with:
          context: .
          load: true
          file: Dockerfile.glibc
          tags: |
            hyperledger/iroha:${{ env.TAG }}
            docker.soramitsu.co.jp/iroha2/iroha:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test docker-compose.single.yml before pushing
        run: |
          docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.single.yml up --wait || exit 1
          docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.single.yml down
      - name: Test docker-compose.local.yml before pushing
        run: |
          docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.local.yml up --wait || exit 1
          docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.local.yml down
      - name: Test docker-compose.yml before pushing
        run: |
          docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.yml up --wait || exit 1
          docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.yml down
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Soramitsu Harbor
        uses: docker/login-action@v3
        with:
          registry: docker.soramitsu.co.jp
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and push iroha2 image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            hyperledger/iroha:${{ env.TAG }}
            docker.soramitsu.co.jp/iroha2/iroha:${{ env.TAG }}
          labels: commit=${{ github.sha }}
